export const GET_USER_MOTIVATION_REQUEST = 'GET_USER_MOTIVATION_REQUEST';
export const GET_USER_MOTIVATION_SUCCESS = 'GET_USER_MOTIVATION_SUCCESS';
export const GET_USER_MOTIVATION_FAILURE = 'GET_USER_MOTIVATION_FAILURE';