export const GET_USER_MOTIVATION_REQUEST = 'GET_USER_MOTIVATION_REQUEST';
export const GET_USER_MOTIVATION_SUCCESS = 'GET_USER_MOTIVATION_SUCCESS';
export const GET_USER_MOTIVATION_FAILURE = 'GET_USER_MOTIVATION_FAILURE';

export const ADD_MOTIVATION_ITEM_REQUEST = 'ADD_MOTIVATION_ITEM_REQUEST';
export const ADD_MOTIVATION_ITEM_SUCCESS = 'ADD_MOTIVATION_ITEM_SUCCESS';
export const ADD_MOTIVATION_ITEM_FAILURE = 'ADD_MOTIVATION_ITEM_FAILURE';