export const SET_PLAN_ACTIVITIES_REQUEST = 'SET_PLAN_ACTIVITIES_REQUEST';
export const SET_PLAN_ACTIVITIES_SUCCESS = 'SET_PLAN_ACTIVITIES_SUCCESS';
export const SET_PLAN_ACTIVITIES_FAILURE = 'SET_PLAN_ACTIVITIES_FAILURE';

export const ADD_PLAN_ACTIVITIES_REQUEST = 'ADD_PLAN_ACTIVITIES_REQUEST';
export const ADD_PLAN_ACTIVITIES_SUCCESS = 'ADD_PLAN_ACTIVITIES_SUCCESS';
export const ADD_PLAN_ACTIVITIES_FAILURE = 'ADD_PLAN_ACTIVITIES_FAILURE';

export const UPDATE_PLAN_ACTIVITY_REQUEST = 'UPDATE_PLAN_ACTIVITY_REQUEST';
export const UPDATE_PLAN_ACTIVITY_SUCCESS = 'UPDATE_PLAN_ACTIVITY_SUCCESS';
export const UPDATE_PLAN_ACTIVITY_FAILURE = 'UPDATE_PLAN_ACTIVITY_FAILURE';

export const UPDATE_USER_PLAN_REQUEST = 'UPDATE_USER_ACTIVITY_REQUEST';
export const UPDATE_USER_PLAN_SUCCESS = 'UPDATE_USER_ACTIVITY_SUCCESS';
export const UPDATE_USER_PLAN_FAILURE = 'UPDATE_USER_ACTIVITY_FAILURE';

export const REMOVE_ACTIVITY_REQUEST = 'REMOVE_ACTIVITY_REQUEST';
export const REMOVE_ACTIVITY_SUCCESS = 'REMOVE_ACTIVITY_SUCCESS';
export const REMOVE_ACTIVITY_FAILURE = 'REMOVE_ACTIVITY_FAILURE';

export const GET_TODAY_PLAN_REQUEST = 'GET_TODAY_PLAN_REQUEST';
export const GET_TODAY_PLAN_SUCCESS = 'GET_TODAY_PLAN_SUCCESS';
export const GET_TODAY_PLAN_FAILURE = 'GET_TODAY_PLAN_FAILURE';

export const GET_TODAY_ACTIVITIES_REQUEST = 'GET_TODAY_ACTIVITIES_REQUEST';
export const GET_TODAY_ACTIVITIES_SUCCESS = 'GET_TODAY_ACTIVITIES_SUCCESS';
export const GET_TODAY_ACTIVITIES_FAILURE = 'GET_TODAY_ACTIVITIES_FAILURE';