
export const ADD_PLAN_ACTIVITIES_REQUEST = 'ADD_PLAN_ACTIVITIES_REQUEST';
export const ADD_PLAN_ACTIVITIES_SUCCESS = 'ADD_PLAN_ACTIVITIES_SUCCESS';
export const ADD_PLAN_ACTIVITIES_FAILURE = 'ADD_PLAN_ACTIVITIES_FAILURE';


export const REMOVE_PLAN_ACTIVITY_REQUEST = 'REMOVE_PLAN_ACTIVITY_REQUEST';
export const REMOVE_PLAN_ACTIVITY_SUCCESS = 'REMOVE_PLAN_ACTIVITY_SUCCESS';
export const REMOVE_PLAN_ACTIVITY_FAILURE = 'REMOVE_PLAN_ACTIVITY_FAILURE';


export const GET_USER_PLAN_FOR_DATE_REQUEST = 'GET_USER_PLAN_FOR_DATE_REQUEST';
export const GET_USER_PLAN_FOR_DATE_SUCCESS = 'GET_USER_PLAN_FOR_DATE_SUCCESS';
export const GET_USER_PLAN_FOR_DATE_FAILURE = 'GET_USER_PLAN_FOR_DATE_FAILURE';

export const UPDATE_PLAN_ACTIVITY_REQUEST = 'UPDATE_PLAN_ACTIVITY_REQUEST';
export const UPDATE_PLAN_ACTIVITY_SUCCESS = 'UPDATE_PLAN_ACTIVITY_SUCCESS';
export const UPDATE_PLAN_ACTIVITY_FAILURE = 'UPDATE_PLAN_ACTIVITY_FAILURE';

export const ADD_PLAN_ACTIVITY_REQUEST = 'ADD_PLAN_ACTIVITY_REQUEST';
export const ADD_PLAN_ACTIVITY_SUCCESS = 'ADD_PLAN_ACTIVITY_SUCCESS';
export const ADD_PLAN_ACTIVITY_FAILURE = 'ADD_PLAN_ACTIVITY_FAILURE';


