export const constants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    RESET_PASS_REQUEST: 'RESET_PASS_REQUEST',
    RESET_PASS_SUCCESS: 'RESET_PASS_SUCCESS',
    RESET_PASS_FAILURE: 'RESET_PASS_FAILURE',

    USERS_GET_ALL_REQUEST: 'USERS_GET_ALL_REQUEST',
    USERS_GET_ALL_SUCCESS: 'USERS_GET_ALL_SUCCESS',
    USERS_GET_ALL_FAILURE: 'USERS_GET_ALL_FAILURE',

    USER_ADD_REQUEST: 'USER_ADD_REQUEST',
    USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
    USER_ADD_FAILURE: 'USER_ADD_FAILURE',

    
    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

    USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCES',
    USER_DELETE_FAILURE: 'USER_DELETE_FAILURE',
}