export const UPDATE_PLAN_ACTIVITY_REQUEST = 'UPDATE_PLAN_ACTIVITY_REQUEST';
export const UPDATE_PLAN_ACTIVITY_SUCCESS = 'UPDATE_PLAN_ACTIVITY_SUCCESS';
export const UPDATE_PLAN_ACTIVITY_FAILURE = 'UPDATE_PLAN_ACTIVITY_FAILURE';

export const GET_TODAY_PLAN_REQUEST = 'GET_TODAY_PLAN_REQUEST';
export const GET_TODAY_PLAN_SUCCESS = 'GET_TODAY_PLAN_SUCCESS';
export const GET_TODAY_PLAN_FAILURE = 'GET_TODAY_PLAN_FAILURE';

export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE';
