export const UPDATE_PLAN_ACTIVITY_REQUEST = 'UPDATE_PLAN_ACTIVITY_REQUEST';
export const UPDATE_PLAN_ACTIVITY_SUCCESS = 'UPDATE_PLAN_ACTIVITY_SUCCESS';
export const UPDATE_PLAN_ACTIVITY_FAILURE = 'UPDATE_PLAN_ACTIVITY_FAILURE';

export const ADD_PLAN_ACTIVITY_REQUEST = 'ADD_PLAN_ACTIVITY_REQUEST';
export const ADD_PLAN_ACTIVITY_SUCCESS = 'ADD_PLAN_ACTIVITY_SUCCESS';
export const ADD_PLAN_ACTIVITY_FAILURE = 'ADD_PLAN_ACTIVITY_FAILURE';

export const GET_ACTIVITY_REQUEST = 'GET_ACTIVITY_REQUEST';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_FAILURE = 'GET_ACTIVITY_FAILURE';
