export {default as auth} from "./auth"
export {default as goals} from "./goal"
export {default as users} from "./user"
export {default as plans} from "./plan"
export {default as exercises} from "./exercise"
export {default as motivations} from "./motivation"