export const USERS_GET_ALL_REQUEST = 'USERS_GET_ALL_REQUEST';
export const USERS_GET_ALL_SUCCESS = 'USERS_GET_ALL_SUCCESS';
export const USERS_GET_ALL_FAILURE = 'USERS_GET_ALL_FAILURE';

export const USER_ADD_REQUEST = 'USER_ADD_REQUEST';
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const USER_ADD_FAILURE = 'USER_ADD_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCES';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';

export const GET_USER_PARAMETERS_REQUEST = 'GET_USER_PARAMETERS_REQUEST';
export const GET_USER_PARAMETERS_SUCCESS = 'GET_USER_PARAMETERS_SUCCESS';
export const GET_USER_PARAMETERS_FAILURE = 'GET_USER_PARAMETERS_FAILURE';

export const SET_USER_GOAL_REQUEST = 'SET_USER_GOAL_REQUEST';
export const SET_USER_GOAL_SUCCESS = 'SET_USER_GOAL_SUCCESS';
export const SET_USER_GOAL_FAILURE = 'SET_USER_GOAL_FAILURE';
