export const SET_USER_GOALS_REQUEST = 'SET_USER_GOALS_REQUEST';
export const SET_USER_GOALS_SUCCESS = 'SET_USER_GOALS_SUCCESS';
export const SET_USER_GOALS_FAILURE = 'SET_USER_GOALS_FAILURE';

export const ADD_USER_GOAL_REQUEST = 'ADD_USER_GOAL_REQUEST';
export const ADD_USER_GOAL_SUCCESS = 'ADD_USER_GOAL_SUCCESS';
export const ADD_USER_GOAL_FAILURE = 'ADD_USER_GOAL_FAILURE';

export const UPDATE_USER_GOAL_REQUEST = 'UPDATE_USER_GOAL_REQUEST';
export const UPDATE_USER_GOAL_SUCCESS = 'UPDATE_USER_GOAL_SUCCESS';
export const UPDATE_USER_GOAL_FAILURE = 'UPDATE_USER_GOAL_FAILURE';

export const UPDATE_GOAL_EXERCISE_REQUEST = 'UPDATE_GOAL_EXERCISE_REQUEST';
export const UPDATE_GOAL_EXERCISE_SUCCESS = 'UPDATE_GOAL_EXERCISE_SUCCESS';
export const UPDATE_GOAL_EXERCISE_FAILURE = 'UPDATE_GOAL_EXERCISE_FAILURE';

export const REMOVE_GOAL_REQUEST = 'REMOVE_GOAL_REQUEST';
export const REMOVE_GOAL_SUCCESS = 'REMOVE_GOAL_SUCCESS';
export const REMOVE_GOAL_FAILURE = 'REMOVE_GOAL_FAILURE';
