export const GET_TODAY_EXERCISE_REQUEST = 'GET_TODAY_EXERCISE_REQUEST';
export const GET_TODAY_EXERCISE_SUCCESS = 'GET_TODAY_EXERCISE_SUCCESS';
export const GET_TODAY_EXERCISE_FAILURE = 'GET_TODAY_EXERCISE_FAILURE';

export const UPDATE_EXERCISE_REQUEST = 'UPDATE_EXERCISE_REQUEST';
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS';
export const UPDATE_EXERCISE_FAILURE = 'UPDATE_EXERCISE_FAILURE';
