export const ADD_NEWS_ITEM_REQUEST = 'ADD_NEWS_ITEM_REQUEST';
export const ADD_NEWS_ITEM_SUCCESS = 'ADD_NEWS_ITEM_SUCCESS';
export const ADD_NEWS_ITEM_FAILURE = 'ADD_NEWS_ITEM_FAILURE';

export const GET_MOTIVATION_ITEM_REQUEST = 'GET_MOTIVATION_ITEM_REQUEST';
export const GET_MOTIVATION_ITEM_SUCCESS = 'GET_MOTIVATION_ITEM_SUCCESS';
export const GET_MOTIVATION_ITEM_FAILURE = 'GET_MOTIVATION_ITEM_FAILURE';